# Generated by Django 4.1 on 2022-10-20 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=4)),
                ('long_url', models.CharField(max_length=500)),
                ('created', models.DateField(default=datetime.datetime(2022, 10, 20, 12, 40, 25, 466204))),
            ],
        ),
    ]
