# Generated by Django 4.1 on 2022-10-21 08:17

import datetime
from django.db import migrations, models
import urlshortener.models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_alter_url_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='expiration',
            field=models.DateField(default=urlshortener.models.return_date_time),
        ),
        migrations.AlterField(
            model_name='url',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
