# Generated by Django 4.1 on 2022-10-21 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_url_expiration_alter_url_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='created',
        ),
    ]
