# Generated by Django 4.1 on 2022-10-21 08:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_remove_url_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='created',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
