# Generated by Django 4.0.4 on 2022-11-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiny',
            name='long_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tiny',
            name='short_url',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
