# Generated by Django 4.0.4 on 2022-11-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorten', '0002_alter_tiny_long_url_alter_tiny_short_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiny',
            name='click_count',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
